package com.example.PacketUtils;

public enum PacketType {
    OPHELDD,
    RESUME_COUNTDIALOG,
    RESUME_PAUSEBUTTON,
    RESUME_NAMEDIALOG,
    RESUME_STRINGDIALOG,
    RESUME_OBJDIALOG,
    IF_BUTTON,
    IF_SUBOP,
    IF_BUTTONX,
    OPNPC,
    OPPLAYER,
    OPOBJ,
    OPLOC,
    MOVE_GAMECLICK,
    EVENT_MOUSE_CLICK,
    IF_BUTTONT,
    OPNPCT,
    OPPLAYERT,
    OPOBJT,
    OPLOCT,
    SET_HEADING
}
